import unittest
import sys
import os

# Add the parent directory to the path so we can import from there
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from chess_logic_by_thomasahle import Position, initial
from test.utils import create_custom_position, is_king_in_check, is_checkmate, is_stalemate

class CheckDetectionTestCase(unittest.TestCase):
    
    def test_king_in_check_detection(self):
        """Test that the engine correctly detects when the king is in check."""
        # 1. Simple check position - white queen checks black king
        check_position = """
        ....k...
        ........
        ........
        ....Q...
        ........
        ........
        ........
        ....K...
        """
        position = create_custom_position(check_position)
        self.assertTrue(is_king_in_check(position), "Black king should be in check by white queen")
        
        # 2. Not in check position
        no_check_position = """
        ....k...
        ........
        ........
        ...Q....
        ........
        ........
        ........
        ....K...
        """
        position = create_custom_position(no_check_position)
        self.assertFalse(is_king_in_check(position), "Black king should not be in check")
        
        # 3. Check by knight
        knight_check_position = """
        ....k...
        ........
        ....N...
        ........
        ........
        ........
        ........
        ....K...
        """
        position = create_custom_position(knight_check_position)
        self.assertTrue(is_king_in_check(position), "Black king should be in check by white knight")
        
        # 4. Check by bishop
        bishop_check_position = """
        ....k...
        ........
        ........
        ........
        .......B
        ........
        ........
        ....K...
        """
        position = create_custom_position(bishop_check_position)
        self.assertTrue(is_king_in_check(position), "Black king should be in check by white bishop")
        
        # 5. Check by rook
        rook_check_position = """
        ....k...
        ....R...
        ........
        ........
        ........
        ........
        ........
        ....K...
        """
        position = create_custom_position(rook_check_position)
        self.assertTrue(is_king_in_check(position), "Black king should be in check by white rook")
        
        # 6. Check by pawn
        pawn_check_position = """
        ....k...
        ...P....
        ........
        ........
        ........
        ........
        ........
        ....K...
        """
        position = create_custom_position(pawn_check_position)
        self.assertTrue(is_king_in_check(position), "Black king should be in check by white pawn")
    
    def test_checkmate_detection(self):
        """Test that the engine correctly detects checkmate positions."""
        # 1. Scholar's mate position
        scholars_mate = """
        r.b.k..r
        pppp.ppp
        ..n.....
        ....p...
        ..B.....
        .....N..
        PPPP.PPP
        R.BQK..R
        """
        # Apply queen move to create checkmate
        position = create_custom_position(scholars_mate)
        # Assuming the move is Qh5
        # We need to modify the position manually
        scholars_mate_after = """
        r.b.k..r
        pppp.ppp
        ..n.....
        ....p..Q
        ..B.....
        .....N..
        PPPP.PPP
        R.B.K..R
        """
        position = create_custom_position(scholars_mate_after)
        self.assertTrue(is_checkmate(position), "Black king should be in checkmate")
        
        # 2. Fool's mate position
        fools_mate = """
        rnbqkbnr
        ppppp.pp
        ........
        .....p..
        .......Q
        ........
        PPPPPPPP
        RNB.KBNR
        """
        position = create_custom_position(fools_mate)
        self.assertTrue(is_checkmate(position), "Black king should be in checkmate in fool's mate")
        
        # 3. Not checkmate - king can move
        not_checkmate = """
        ....k...
        ........
        ........
        ....Q...
        ........
        ........
        ........
        ....K...
        """
        position = create_custom_position(not_checkmate)
        self.assertFalse(is_checkmate(position), "Black king can move, so not checkmate")
        
        # 4. Not checkmate - piece can block
        not_checkmate_can_block = """
        ....k...
        ....r...
        ........
        ....Q...
        ........
        ........
        ........
        ....K...
        """
        position = create_custom_position(not_checkmate_can_block)
        self.assertFalse(is_checkmate(position), "Black rook can block, so not checkmate")
        
        # 5. Not checkmate - piece can capture
        not_checkmate_can_capture = """
        ....k...
        ........
        ........
        ...rQ...
        ........
        ........
        ........
        ....K...
        """
        position = create_custom_position(not_checkmate_can_capture)
        self.assertFalse(is_checkmate(position), "Black rook can capture queen, so not checkmate")
    
    def test_stalemate_detection(self):
        """Test that the engine correctly detects stalemate positions."""
        # 1. Classic stalemate position
        stalemate_position = """
        .......k
        .......P
        ........
        ........
        ........
        ........
        ........
        K.......
        """
        position = create_custom_position(stalemate_position)
        self.assertTrue(is_stalemate(position), "Black king has no legal moves and is not in check, so stalemate")
        
        # 2. Another stalemate position
        stalemate_position2 = """
        .......k
        .......Q
        ........
        ........
        ........
        ........
        ........
        K.......
        """
        position = create_custom_position(stalemate_position2)
        self.assertTrue(is_stalemate(position), "Black king has no legal moves and is not in check, so stalemate")
        
        # 3. Not stalemate - king can move
        not_stalemate = """
        ......k.
        .......Q
        ........
        ........
        ........
        ........
        ........
        K.......
        """
        position = create_custom_position(not_stalemate)
        self.assertFalse(is_stalemate(position), "Black king can move, so not stalemate")
        
        # 4. Not stalemate - other pieces can move
        not_stalemate2 = """
        .......k
        .......Q
        ........
        ........
        .....r..
        ........
        ........
        K.......
        """
        position = create_custom_position(not_stalemate2)
        self.assertFalse(is_stalemate(position), "Black has rook that can move, so not stalemate")
        
        # 5. Not stalemate - in check
        not_stalemate3 = """
        .......k
        ........
        .......Q
        ........
        ........
        ........
        ........
        K.......
        """
        position = create_custom_position(not_stalemate3)
        self.assertFalse(is_stalemate(position), "Black king is in check, so not stalemate")

if __name__ == '__main__':
    unittest.main() 